[theme]
name = "catppuccin-latte-teal"

[colors]
AlertInfo = "#40a02b"
AlertWarn = "#df8e1d"
AlertError = "#d20f39"
Annotation = "#179299"
Base = "#4c4f69"
Guidance = "#179299"
Important = "#179299"
Title = "#179299"
