[theme]
name = "catppuccin-frappe-yellow"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#e5c890"
Base = "#c6d0f5"
Guidance = "#e5c890"
Important = "#e5c890"
Title = "#e5c890"
