[theme]
name = "catppuccin-frappe-red"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#e78284"
Base = "#c6d0f5"
Guidance = "#e78284"
Important = "#e78284"
Title = "#e78284"
