[theme]
name = "catppuccin-frappe-pink"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#f4b8e4"
Base = "#c6d0f5"
Guidance = "#f4b8e4"
Important = "#f4b8e4"
Title = "#f4b8e4"
