[theme]
name = "catppuccin-frappe-blue"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#8caaee"
Base = "#c6d0f5"
Guidance = "#8caaee"
Important = "#8caaee"
Title = "#8caaee"
