[theme]
name = "catppuccin-frappe-sky"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#99d1db"
Base = "#c6d0f5"
Guidance = "#99d1db"
Important = "#99d1db"
Title = "#99d1db"
