[theme]
name = "catppuccin-frappe-lavender"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#babbf1"
Base = "#c6d0f5"
Guidance = "#babbf1"
Important = "#babbf1"
Title = "#babbf1"
