[theme]
name = "catppuccin-frappe-flamingo"

[colors]
AlertInfo = "#a6d189"
AlertWarn = "#e5c890"
AlertError = "#e78284"
Annotation = "#eebebe"
Base = "#c6d0f5"
Guidance = "#eebebe"
Important = "#eebebe"
Title = "#eebebe"
