[theme]
name = "catppuccin-macchiato-peach"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#f5a97f"
Base = "#cad3f5"
Guidance = "#f5a97f"
Important = "#f5a97f"
Title = "#f5a97f"
