[theme]
name = "catppuccin-macchiato-teal"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#8bd5ca"
Base = "#cad3f5"
Guidance = "#8bd5ca"
Important = "#8bd5ca"
Title = "#8bd5ca"
