[theme]
name = "catppuccin-macchiato-red"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#ed8796"
Base = "#cad3f5"
Guidance = "#ed8796"
Important = "#ed8796"
Title = "#ed8796"
