[theme]
name = "catppuccin-macchiato-rosewater"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#f4dbd6"
Base = "#cad3f5"
Guidance = "#f4dbd6"
Important = "#f4dbd6"
Title = "#f4dbd6"
