[theme]
name = "catppuccin-macchiato-sky"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#91d7e3"
Base = "#cad3f5"
Guidance = "#91d7e3"
Important = "#91d7e3"
Title = "#91d7e3"
