[theme]
name = "catppuccin-macchiato-blue"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#8aadf4"
Base = "#cad3f5"
Guidance = "#8aadf4"
Important = "#8aadf4"
Title = "#8aadf4"
