[theme]
name = "catppuccin-macchiato-lavender"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#b7bdf8"
Base = "#cad3f5"
Guidance = "#b7bdf8"
Important = "#b7bdf8"
Title = "#b7bdf8"
