[theme]
name = "catppuccin-macchiato-sapphire"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#7dc4e4"
Base = "#cad3f5"
Guidance = "#7dc4e4"
Important = "#7dc4e4"
Title = "#7dc4e4"
