[theme]
name = "catppuccin-macchiato-green"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eed49f"
AlertError = "#ed8796"
Annotation = "#a6da95"
Base = "#cad3f5"
Guidance = "#a6da95"
Important = "#a6da95"
Title = "#a6da95"
