[theme]
name = "catppuccin-mocha-red"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#f38ba8"
Base = "#cdd6f4"
Guidance = "#f38ba8"
Important = "#f38ba8"
Title = "#f38ba8"
