[theme]
name = "catppuccin-mocha-peach"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#fab387"
Base = "#cdd6f4"
Guidance = "#fab387"
Important = "#fab387"
Title = "#fab387"
