[theme]
name = "catppuccin-mocha-flamingo"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#f2cdcd"
Base = "#cdd6f4"
Guidance = "#f2cdcd"
Important = "#f2cdcd"
Title = "#f2cdcd"
