[theme]
name = "catppuccin-mocha-rosewater"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#f5e0dc"
Base = "#cdd6f4"
Guidance = "#f5e0dc"
Important = "#f5e0dc"
Title = "#f5e0dc"
